//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyC.GestorDeContactos.AccesoDatos.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public Provincia()
        {
            this.Direccion = new HashSet<Direccion>();
        }
    
        public System.Guid UIDProvincia { get; set; }
        public string Codigo { get; set; }
        public string Provincia1 { get; set; }
    
        public virtual ICollection<Direccion> Direccion { get; set; }
    }
}
